server:
  port: ${PORT:8083}

spring:
  datasource:
    url: ${DATA_BASE_URL:jdbc:postgresql://127.0.0.1:5433/nurairbnbc}
    username: ${DATA_BASE_USERNAME:postgres}
    password: ${DATA_BASE_PASSWORD:Estudiar1995}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /
